# Generated by Django 4.2.5 on 2023-09-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapi',
            name='pwd',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
